name: TestConfig

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Boost
      id: boost
      uses: egor-tensin/build-boost@v1
      with:
        version: 1.74.0
        libraries: filesystem program_options thread
        configuration: Release

    - name: Install Gtest
      run: |
        sudo apt-get install libgtest-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make 
        sudo cp lib/*.a /usr/lib
        sudo ln -s /usr/lib/libgtest.a /usr/local/lib/libgtest.a
        sudo ln -s /usr/lib/libgtest_main.a /usr/local/lib/libgtest_main.a

    - name: Build project
      # Build your program with the given configuration
      working-directory: ${{github.workspace}}
      run: |
        mkdir build
        cd build
        cmake -DUNIT_TESTS=ON ..
        make

    - name: UT Tests
      working-directory: ${{github.workspace}}/build/test
      # Execute tests defined by the CMake configuration.
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: |
        ./UT_SpecificGrep
